# Generated by Django 4.2 on 2024-02-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='detalls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='inici',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='lliga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ligas.liga'),
        ),
        migrations.AddField(
            model_name='partido',
            name='local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partits_local', to='ligas.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='visitant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partits_visitant', to='ligas.equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='partido',
            unique_together={('local', 'visitant', 'lliga')},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.TimeField()),
                ('tipus', models.CharField(choices=[('GOL', 'Gol'), ('AUTOGOL', 'Autogol'), ('FALTA', 'Falta'), ('PENALTY', 'Penalty'), ('MANS', 'Mans'), ('CESSIO', 'Cessio'), ('FORA_DE_JOC', 'Fora De Joc'), ('ASSISTENCIA', 'Assistencia'), ('TARGETA_GROGA', 'Targeta Groga'), ('TARGETA_VERMELLA', 'Targeta Vermella')], max_length=30)),
                ('detalls', models.TextField(blank=True, null=True)),
                ('Partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligas.partido')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ligas.equipo')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fets', to='ligas.jugador')),
                ('jugador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_rebuts', to='ligas.jugador')),
            ],
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='resultado_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='resultado_visitante',
        ),
    ]
